### ISSUE TITLE
Bounds checking does not look right

### ISSUE THREAD

**Issue by nsubburaj** [nishihatapalmer/byteseek#14]
Bounds checking condition in the file ListMultiSequenceMatcher.java(Line no:169) doesn't look good

**Comment by nishihatapalmer** [comment]
Hi, no it doesn't - there's already a comment that it needs fixing!

None of the multi-sequence matchers or searchers are currently tested, but I do intend to do after the next release of byteseek, which should hopefully be fairly soon.  That will also mean looking at the automata classes as well.  When that's all done, the whole of byteseek as it currently stands should be in good shape.

**Comment by nishihatapalmer** [comment]
If you want to submit a PR, I'll happily look at it :)
