### ISSUE TITLE
Typo: "first" should be "last" in syntax.md page

### ISSUE THREAD

**Issue by jrwdunham** [nishihatapalmer/byteseek#15]
On the https://github.com/nishihatapalmer/byteseek/blob/master/syntax.md page where it is written:

     &7f                 # 0x7f = 01111111. Match bytes with all first seven bits set.

I think "first" should be "last", i.e.:

     &7f                 # 0x7f = 01111111. Match bytes with all last seven bits set.

**Comment by jrwdunham** [comment]
Oops. Duh. The original wording is correct. I'm reading my binary backwards. Sorry for the noise. Closing.

**Comment by nishihatapalmer** [comment]
Hey, no problem.  Thanks for trying to improve byteseek!

**Comment by jrwdunham** [comment]
@nishihatapalmer Thanks. Without opening another new issue, is the line `^~87                # 0x87 = 10000111. Match bytes without any of the bitmask bits set.` on the same syntax.md page correct? It seems to me that `^~87` should match all bytes with the first three and the last bits unset, i.e., 


    00000000
    00001000
    00010000
    00011000
    00100000
    00101000
    00110000
    00111000
    01000000
    01001000
    01010000
    01011000
    01100000
    01101000
    01110000
    01111000

Am I missing something here again?

**Comment by nishihatapalmer** [comment]
That's correct.  An any match ~87 on its own would match all the bytes with any of those bits set, but the expression is negated with ^, so it will match all bytes without any of those bits set, which is the list you give.

**Comment by nishihatapalmer** [comment]
A simple way to understand the negation operator ^ is that it gives you a set of bytes containing all the bytes which weren't in the original set.

**Comment by jrwdunham** [comment]
Oh, yes, I understand the semantics of `~`, `^`, and `&`; I was confused about the wording, but now I see that "without any of the bitmask bits set" means "without any of the bits in `10000111` set", i.e., all integers between 0 and 255 whose binary representation (as a string) starts with `0` and ends with `000`.

**Comment by nishihatapalmer** [comment]
I can see how it could be confusing... I'll either have to come up with some better examples, or a better explanation...
